# Generated by Django 6.0.1 on 2026-01-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='file/notices/')),
            ],
        ),
    ]
