# Generated by Django 6.0.1 on 2026-01-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='pdf_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='file/notices/'),
        ),
    ]
