# Generated by Django 6.0.1 on 2026-01-24 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_notice_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(blank=True, max_length=500, null=True, upload_to='file/results/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(max_length=7, unique=True)),
                ('gpa1', models.FloatField(default=0.0)),
                ('gpa2', models.FloatField(default=0.0)),
                ('gpa3', models.FloatField(default=0.0)),
                ('gpa4', models.FloatField(default=0.0)),
                ('gpa5', models.FloatField(default=0.0)),
                ('gpa6', models.FloatField(default=0.0)),
                ('gpa7', models.FloatField(default=0.0)),
                ('gpa8', models.FloatField(default=0.0)),
            ],
        ),
    ]
