# Generated by Django 6.0.1 on 2026-01-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_resultpdf_studentresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentResult',
        ),
        migrations.AddField(
            model_name='resultpdf',
            name='json_data',
            field=models.FileField(blank=True, null=True, upload_to='file/results/json/'),
        ),
        migrations.AlterField(
            model_name='resultpdf',
            name='pdf_file',
            field=models.FileField(upload_to='file/results/'),
        ),
    ]
