# Generated by Django 6.0.1 on 2026-01-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_delete_studentresult_resultpdf_json_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.IntegerField(unique=True)),
                ('gpa1', models.CharField(blank=True, max_length=10, null=True)),
                ('gpa2', models.CharField(blank=True, max_length=10, null=True)),
                ('gpa3', models.CharField(blank=True, max_length=10, null=True)),
                ('gpa4', models.CharField(blank=True, max_length=10, null=True)),
                ('gpa5', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='resultpdf',
            name='json_data',
        ),
        migrations.RemoveField(
            model_name='resultpdf',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='resultpdf',
            name='pdf',
            field=models.FileField(default=1, upload_to='results_pdfs/'),
            preserve_default=False,
        ),
    ]
