# Generated by Django 6.0.1 on 2026-01-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_studentresult_remove_resultpdf_json_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='gpa6',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='gpa7',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
