# Generated by Django 6.0.1 on 2026-01-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_headline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headline',
            name='text',
            field=models.TextField(),
        ),
    ]
